test.changes: fix case ddoc without filters+key (#8775)
Improves unstable behaviour in "Changes with filters key not present in ddoc"
caused by a TypeError in ci:

```
TypeError: Cannot read properties of undefined (reading 'should')
    at Changes$1.<anonymous> (http://127.0.0.1:8000/tests/integration/test.changes.js:358:22)
    2) "after each" hook for "Changes with `filters` key not present in ddoc"
    at emitOne (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.js:115:13)

    at Changes$1.emit (http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.js:193:7)

    at http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.js:4347:16

    at http://127.0.0.1:8000/packages/node_modules/pouchdb/dist/pouchdb.js:2897:11
```

Root of this error seems to be an unpolluted (chai's .should getter/setter on Object.prototype) `err` argument.